# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
  # - stage: "Build"
  #   displayName: "Build the application"
  #   jobs:
  #     - job: 'Build'
  #       displayName: "Build Job"
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #       - script: "docker compose build"
  #         displayName: "Docker Build"
  #       - script: "docker login -u $(DOCKER_NAME)-p $(DOCKER_PASSWORD)"
  #         displayName: "Docker Login"
  #       - script: "docker compose push"
  #         displayName: "Docker Push"
  - stage: "Deploy"
    # dependsOn: Build
    # condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: agent-1
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: docker compose up -d
